version: '3'

services:

  face-service:
    build: .
    links:
      - mysqldb
    ports:
      - '5001:5001'
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '2138'
    volumes:
      - ~/docker_storage/mysql:/var/lib/mysql
      # If you would like to do additional initialization in
      # an image derived from this one, add one or more *.sql,
      # *.sql.gz, or *.sh scripts under /docker-entrypoint-initdb.d
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql





